-- 1. Create categories table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create tags table
CREATE TABLE IF NOT EXISTS tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Add new columns to products table if they don't exist
ALTER TABLE products ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS short_description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS styling TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS occasions TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS metal_type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gold_purity TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gold_color TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gross_weight TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS net_gold_weight TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS diamond_type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS total_diamond_weight TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS diamond_shape TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS diamond_color TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS diamond_clarity TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS number_of_diamonds INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gemstone_type TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gemstone_shape TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS gemstone_size TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS total_gemstone_weight TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS number_of_gemstones INTEGER;
ALTER TABLE products ADD COLUMN IF NOT EXISTS origin TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS treatment TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS dimensions TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS ring_size TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS necklace_length TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_status TEXT DEFAULT 'In Stock';
ALTER TABLE products ADD COLUMN IF NOT EXISTS production_time TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS certification TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS hallmark_details TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS shipping_info TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_title TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS seo_description TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

-- 4. Seed default categories if empty
INSERT INTO categories (name, slug)
VALUES 
  ('Signature Collection', 'signature-collection'),
  ('HardWear', 'hardwear'),
  ('Smile', 'smile'),
  ('T1', 't1'),
  ('Lock', 'lock'),
  ('High Jewelry', 'high-jewelry')
ON CONFLICT (name) DO NOTHING;

-- 5. Seed default tags if empty
INSERT INTO tags (name, slug)
VALUES 
  ('Gold', 'gold'),
  ('Diamond', 'diamond'),
  ('Rose Gold', 'rose-gold'),
  ('White Gold', 'white-gold'),
  ('Yellow Gold', 'yellow-gold'),
  ('Pendant', 'pendant'),
  ('Bracelet', 'bracelet'),
  ('Necklace', 'necklace'),
  ('Ring', 'ring')
ON CONFLICT (name) DO NOTHING;
